<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWDzGA3h\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWDzGA3h/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWDzGA3h.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWDzGA3h\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWDzGA3h\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WDzGA3h',
    'container.build_id' => '69229b0f',
    'container.build_time' => 1650522413,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWDzGA3h');
