<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZMjcFGS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZMjcFGS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZMjcFGS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZMjcFGS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZMjcFGS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZMjcFGS',
    'container.build_id' => '9ba1f9b8',
    'container.build_time' => 1650510640,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZMjcFGS');
